<!--- Generated by Adobe Dreamweaver CS3 9.0.0.3481 [en] (Win32) - Mon Jan 05 2009 21:02:11 GMT-0800 (Pacific Standard Time) --->

<cfcomponent displayName="eventData2">
	<cffunction name="eventInfo" access="public" returnType="query" output="false">
		<cfargument name="eventDate" type="date" required="true">
		<!--- eventInfo body --->
		<cfreturn >
	</cffunction>
</cfcomponent>